
#!/usr/bin/env python3
"""
PID Debug Plots - generated by BallbotCascadeController::plotDebugLogs
X-axis = time (s)
Blue solid = target
Red dashed = actual
"""
import matplotlib.pyplot as plt
import numpy as np
import csv
import os
import sys

# Color config
COLOR_TARGET = '#1f77b4'   # blue
COLOR_ACTUAL = '#d62728'   # red
COLOR_PID_OUT = '#2ca02c'  # green (PID output)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# 4-loop config: (文件名, 显示名, 维度, 各轴标签)
LOOP_CONFIGS = [
    ("pid_debug_Layer1_Velocity.csv",  "Layer1: Velocity -> Tilt",   2,
     ["vx (m/s)", "vy (m/s)"],
     ["pitch_des", "roll_des"]),
    ("pid_debug_Layer1b_Yaw.csv",      "Layer1b: Yaw -> wz_cmd", 1,
     ["wz (rad/s)"],
     ["wz_cmd"]),
    ("pid_debug_Layer2_Attitude.csv",  "Layer2: Attitude -> Virtual Vel", 2,
     ["pitch (rad)", "roll (rad)"],
     ["vx_cmd (m/s)", "vy_cmd (m/s)"]),
    ("pid_debug_Layer4_Wheel.csv",     "Layer4: Wheel Vel -> Torque",    3,
     ["w1 (rad/s)", "w2 (rad/s)", "w3 (rad/s)"],
     ["tau1 (N.m)", "tau2 (N.m)", "tau3 (N.m)"]),
]


def read_csv(filepath):
    """Read CSV and return {col_name: [values]}"""
    if not os.path.exists(filepath):
        print(f"  [SKIP] file not found: {filepath}")
        return None

    with open(filepath, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        if not rows:
            print(f"  [SKIP] file empty: {filepath}")
            return None

    # build column data
    data = {}
    for key in rows[0].keys():
        data[key.strip()] = [float(row[key]) for row in rows]

    data['_nrows'] = len(rows)
    print(f"  Read: {filepath}  ({data['_nrows']} rows)")
    return data


def plot_loop(data, title, dim, axis_labels, output_labels, save_path):
    """Generate one figure per PID loop, dim subplots horizontally"""
    fig, axes = plt.subplots(1, dim, figsize=(6 * dim, 5), squeeze=False)
    axes = axes[0]  # flatten to 1D array

    time = np.array(data['timestamp'])

    for d in range(dim):
        ax = axes[d]
        idx = f'[{d}]' if dim > 1 else ''

        # read target / actual / output
        target = np.array(data[f'target{idx}'])
        actual = np.array(data[f'actual{idx}'])
        output = np.array(data[f'output{idx}'])

        # target (solid blue)
        ax.plot(time, target, color=COLOR_TARGET, linewidth=1.2, label='target')
        # actual (dashed red)
        ax.plot(time, actual, color=COLOR_ACTUAL, linewidth=1.2,
                linestyle='--', dashes=(4, 2), label='actual')

        ax.set_xlabel('Time (s)')
        ax.set_ylabel(axis_labels[d])
        ax.set_title(f'{axis_labels[d]} — Tracking')
        ax.legend(loc='best', fontsize=8)
        ax.grid(True, alpha=0.3)

        # secondary Y axis: PID output
        ax2 = ax.twinx()
        ax2.plot(time, output, color=COLOR_PID_OUT, linewidth=0.6,
                 alpha=0.5, label='PID output')
        ax2.set_ylabel('Output', color=COLOR_PID_OUT, fontsize=8)
        ax2.tick_params(axis='y', labelcolor=COLOR_PID_OUT, labelsize=7)

    fig.suptitle(title, fontsize=13, fontweight='bold')
    plt.tight_layout()
    fig.savefig(save_path, dpi=150)
    print(f"  → Saved: {save_path}")
    plt.close(fig)


def main():
    print("=" * 60)
    print("  PID Debug Plot")
    print("=" * 60)

    for csv_name, title, dim, axis_labels, output_labels in LOOP_CONFIGS:
        print(f"\n[{title}]")
        filepath = os.path.join(SCRIPT_DIR, csv_name)
        data = read_csv(filepath)
        if data is None:
            continue

        png_name = csv_name.replace('.csv', '.png')
        png_path = os.path.join(SCRIPT_DIR, png_name)
        plot_loop(data, title, dim, axis_labels, output_labels, png_path)

    print(f"\n{'=' * 60}")
    print(f"  Done! Images saved in: {SCRIPT_DIR}")
    print(f"{'=' * 60}")


if __name__ == '__main__':
    main()
